In [1]:
import pandas as pd
import psycopg2

In [2]:
data1=pd.read_csv('anime.csv',index_col=False)
data2=pd.read_csv('rating.csv',index_col=False)

In [3]:
df=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [4]:
merge1 = pd.merge(df,df2, on="anime_id")
merge1

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278,-1
...,...,...,...,...,...,...,...,...,...
7813722,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,39532,-1
7813723,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,48766,-1
7813724,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365,4
7813725,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,27364,-1
7813726,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,48766,-1

In [5]:
l=merge1.sort_values(by=['anime_id'])

In [6]:
l

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
208695,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,51593,9
213578,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,72958,8
213579,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73004,8
213580,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73013,8
213581,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73014,10
...,...,...,...,...,...,...,...,...,...
7287761,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,53492,5
7287762,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,70547,9
7287763,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,70768,-1
7688655,34476,Platonic Chain: Ansatsu Jikkouchuu,"Sci-Fi, Slice of Life",Special,1,1.67,51,48766,-1
7688107,34519,Mobile Suit Gakuen: G-Reco Koushien,Comedy,Special,9,5.67,94,48766,-1

In [7]:
l.rename(columns={'name':'anime_name', 'rating_x':'anime_rating','rating_y':'user_ratings'},inplace=True)

In [8]:
l

,anime_id,anime_name,genre,type,episodes,anime_rating,members,user_id,user_ratings
208695,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,51593,9
213578,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,72958,8
213579,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73004,8
213580,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73013,8
213581,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73014,10
...,...,...,...,...,...,...,...,...,...
7287761,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,53492,5
7287762,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,70547,9
7287763,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,70768,-1
7688655,34476,Platonic Chain: Ansatsu Jikkouchuu,"Sci-Fi, Slice of Life",Special,1,1.67,51,48766,-1
7688107,34519,Mobile Suit Gakuen: G-Reco Koushien,Comedy,Special,9,5.67,94,48766,-1

In [10]:
anime_state = l.drop(["anime_id","genre", "type", "episodes",'anime_rating','members','user_id'], axis=1)
anime_state

                                  anime_name  user_ratings
208695                          Cowboy Bebop             9
213578                          Cowboy Bebop             8
213579                          Cowboy Bebop             8
213580                          Cowboy Bebop             8
213581                          Cowboy Bebop            10
...                                      ...           ...
7287761     Monster Strike: Rain of Memories             5
7287762     Monster Strike: Rain of Memories             9
7287763     Monster Strike: Rain of Memories            -1
7688655   Platonic Chain: Ansatsu Jikkouchuu            -1
7688107  Mobile Suit Gakuen: G-Reco Koushien            -1

[7813727 rows x 2 columns]

In [18]:
anime_avg_ratings=anime_state.groupby(['anime_name']).mean().sort_values(['user_ratings'],ascending=False)
anime_avg_rating=anime_avg_ratings.rename(columns={'user_ratings': 'avg_rating'})

In [19]:
anime_avg_rating

                                                    avg_rating
anime_name
Choegang Top Plate                                        10.0
STAR BEAT!: Hoshi no Kodou                                10.0
Shiroi Zou                                                10.0
Warui no wo Taose!! Salaryman Man                         10.0
Yakushiji Ryouko no Kaiki Jikenbo: Hamachou, Vo...         9.0
...                                                        ...
Kyoufu no Kyou-chan                                       -1.0
Hana no Zundamaru                                         -1.0
Hana to Shounen                                           -1.0
Pro Yakyuu wo 10-bai Tanoshiku Miru Houhou Part 2         -1.0
Mikosuri Han-Gekijou                                      -1.0

[11196 rows x 1 columns]

In [20]:
anime_avg_rating.to_csv('anime_avg_rating.csv')

In [12]:
l.to_csv('AAnime.csv',index=False)

In [21]:
import psycopg2

In [24]:
l.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7813727 entries, 208695 to 7688107
Data columns (total 9 columns):
 #   Column        Dtype
---  ------        -----
 0   anime_id      int64
 1   anime_name    object
 2   genre         object
 3   type          object
 4   episodes      object
 5   anime_rating  float64
 6   members       int64
 7   user_id       int64
 8   user_ratings  int64
dtypes: float64(1), int64(4), object(4)
memory usage: 596.1+ MB

In [28]:
p=pd.DataFrame(l)

In [29]:
import psycopg2
import pandas as pd

def connect():
    try:
        conn = psycopg2.connect(
            dbname="postgres",
            user="postgres",
            password="root",
            host="127.0.0.1",
            port="5432"
        )
        return conn
    except psycopg2.Error as e:
        print("Unable to connect to the database.")
        print(e)
        return None

def create_table(conn):
    try:
        cur = conn.cursor()
        cur.execute("""
            CREATE TABLE IF NOT EXISTS anime (
                anime_id INT PRIMARY KEY NOT NULL,
                anime_name TEXT,
                genre TEXT,
                type TEXT,
                episodes INT,
                anime_rating DOUBLE PRECISION,
                members INT,
                user_id INT,
                user_ratings INT
            );
        """)
        conn.commit()
        cur.close()
    except psycopg2.Error as e:
        print("Error creating table.")
        print(e)

# Function to insert data
def insert_data(conn, data):
    try:
        cur = conn.cursor()
        # Insert data into the table
        cur.execute("""
            INSERT INTO anime (
                anime_id,
                anime_name,
                type,
                genre,
                episodes,
                anime_rating,
                members,
                user_id,
                user_ratings
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);
        """, data)
        conn.commit()
        cur.close()
    except psycopg2.Error as e:
        print("Error inserting data.")
        print(e)

# Main function
def main():
    # Load data from CSV file
    df = p # Replace "your_data.csv" with your CSV file path
    
    # Connect to PostgreSQL
    conn = connect()
    if conn is None:
        return
    
    # Create table
    create_table(conn)

    # Insert data into the table
    for index, row in df.iterrows():
        data = (row['anime_id'], row['anime_name'], row['type'], row['genre'], row['episodes'], row['anime_rating'], row['members'], row['user_id'], row['user_ratings'])
        insert_data(conn, data)

    # Close connection
    conn.close()

if __name__ == "__main__":
    main()

,anime_id,anime_name,genre,type,episodes,anime_rating,members,user_id,user_ratings
208695,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,51593,9
213578,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,72958,8
213579,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73004,8
213580,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73013,8
213581,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824,73014,10
...,...,...,...,...,...,...,...,...,...
7287761,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,53492,5
7287762,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,70547,9
7287763,34475,Monster Strike: Rain of Memories,"Action, Fantasy, Game",ONA,1,6.58,313,70768,-1
7688655,34476,Platonic Chain: Ansatsu Jikkouchuu,"Sci-Fi, Slice of Life",Special,1,1.67,51,48766,-1
7688107,34519,Mobile Suit Gakuen: G-Reco Koushien,Comedy,Special,9,5.67,94,48766,-1